name: Metrics embed

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/metrics.yml
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Your GitHub token
          # The following scopes are required:
          #  - public_access (default scope)
          # The following additional scopes may be required:
          #  - read:org      (for organization related metrics)
          #  - read:user     (for user related data)
          #  - read:packages (for some packages related data)
          #  - repo          (optional, if you want to include private repositories)
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: mboxlab
          filename: profile/metrics.svg
          
          template: classic
          base: header, activity, community, repositories, metadata
          config_octicon: yes
          config_twemoji: yes
          
          plugin_languages: yes
          plugin_languages_details: percentage, lines
          plugin_languages_sections: most-used, recently-used
          plugin_languages_other: true
        
          plugin_notable: yes
          plugin_notable_from: all
          plugin_notable_repositories: yes
          plugin_notable_self: yes
          plugin_notable_types: commit
